# Polars Introduction

In [1]:
import polars as pl

In [3]:
df = pl.read_csv('course_file.csv', has_header=True)

In [7]:
df.head(2)

shape: (2, 12)
┌────────────┬───────────────┬──────────────────┬─────────┬───┬──────────┬─────────────┬──────────────┬──────────┐
│ date_time  ┆ userid        ┆ domain           ┆ dlbytes ┆ … ┆ txn_time ┆ http_method ┆ user_agent   ┆ platform │
│ ---        ┆ ---           ┆ ---              ┆ ---     ┆   ┆ ---      ┆ ---         ┆ ---          ┆ ---      │
│ str        ┆ i64           ┆ str              ┆ i64     ┆   ┆ f64      ┆ str         ┆ str          ┆ str      │
╞════════════╪═══════════════╪══════════════════╪═════════╪═══╪══════════╪═════════════╪══════════════╪══════════╡
│ 2023-10-04 ┆ 7773153683656 ┆ ryan-wells.co.uk ┆ 872807  ┆ … ┆ 2.33     ┆ HTTPS       ┆ Mozilla/5.0  ┆ Android  │
│ 11:37:11   ┆               ┆                  ┆         ┆   ┆          ┆             ┆ (Windows; U; ┆          │
│            ┆               ┆                  ┆         ┆   ┆          ┆             ┆ Windows…     ┆          │
│ 2023-10-04 ┆ 1886351675683 ┆ hopkins.org      ┆ 50898   ┆ … ┆ 1.2      ┆ HTTP        ┆ Mozilla/5.0  ┆ Android  │
│ 12:17:07   ┆               ┆                  ┆         ┆   ┆          ┆             ┆ (Windows; U; ┆          │
│            ┆               ┆                  ┆         ┆   ┆          ┆             ┆ Windows…     ┆          │
└────────────┴───────────────┴──────────────────┴─────────┴───┴──────────┴─────────────┴──────────────┴──────────┘

In [8]:
df.tail(2)

shape: (2, 12)
┌────────────┬───────────────┬───────────────────┬─────────┬───┬──────────┬─────────────┬───────────────────┬──────────┐
│ date_time  ┆ userid        ┆ domain            ┆ dlbytes ┆ … ┆ txn_time ┆ http_method ┆ user_agent        ┆ platform │
│ ---        ┆ ---           ┆ ---               ┆ ---     ┆   ┆ ---      ┆ ---         ┆ ---               ┆ ---      │
│ str        ┆ i64           ┆ str               ┆ i64     ┆   ┆ f64      ┆ str         ┆ str               ┆ str      │
╞════════════╪═══════════════╪═══════════════════╪═════════╪═══╪══════════╪═════════════╪═══════════════════╪══════════╡
│ 2023-10-04 ┆ 3489765231586 ┆ clarke-parsons.co ┆ 757315  ┆ … ┆ 2.54     ┆ HTTP        ┆ Opera/8.27.(X11;  ┆ Linux    │
│ 05:26:28   ┆               ┆ .uk               ┆         ┆   ┆          ┆             ┆ Linux x86_64; a…  ┆          │
│ 2023-10-04 ┆ 4668345200091 ┆ cox.com           ┆ 295770  ┆ … ┆ 2.62     ┆ HTTP        ┆ Mozilla/5.0 (X11; ┆ Linux    │
│ 20:40:11   ┆               ┆                   ┆         ┆   ┆          ┆             ┆ Linux x86_64; …   ┆          │
└────────────┴───────────────┴───────────────────┴─────────┴───┴──────────┴─────────────┴───────────────────┴──────────┘

In [9]:
len(df)

100000

In [10]:
print(df.columns)

['date_time', 'userid', 'domain', 'dlbytes', 'ulbytes', 'clientip', 'serverip', 'country', 'txn_time', 'http_method', 'user_agent', 'platform']

In [11]:
print(df.dtypes)

[Utf8, Int64, Utf8, Int64, Int64, Utf8, Utf8, Utf8, Float64, Utf8, Utf8, Utf8]

In [14]:
print(df.shape)

(100000, 12)

In [18]:
print(df.describe())

shape: (9, 13)
┌────────────┬────────────┬─────────────┬───────────────────┬───┬──────────┬─────────────┬──────────────────┬──────────┐
│ describe   ┆ date_time  ┆ userid      ┆ domain            ┆ … ┆ txn_time ┆ http_method ┆ user_agent       ┆ platform │
│ ---        ┆ ---        ┆ ---         ┆ ---               ┆   ┆ ---      ┆ ---         ┆ ---              ┆ ---      │
│ str        ┆ str        ┆ f64         ┆ str               ┆   ┆ f64      ┆ str         ┆ str              ┆ str      │
╞════════════╪════════════╪═════════════╪═══════════════════╪═══╪══════════╪═════════════╪══════════════════╪══════════╡
│ count      ┆ 100000     ┆ 100000.0    ┆ 100000            ┆ … ┆ 100000.0 ┆ 100000      ┆ 100000           ┆ 100000   │
│ null_count ┆ 0          ┆ 0.0         ┆ 0                 ┆ … ┆ 0.0      ┆ 0           ┆ 0                ┆ 0        │
│ mean       ┆ null       ┆ 5.0101e12   ┆ null              ┆ … ┆ 1.498052 ┆ null        ┆ null             ┆ null     │
│ std        ┆ null       ┆ 2.8983e12   ┆ null              ┆ … ┆ 0.866925 ┆ null        ┆ null             ┆ null     │
│ min        ┆ 2023-10-01 ┆ 3.4807482e7 ┆ abbott-barnes.com ┆ … ┆ 0.0      ┆ HTTP        ┆ Mozilla/5.0      ┆ Android  │
│            ┆ 00:00:01   ┆             ┆                   ┆   ┆          ┆             ┆ (Android 1.0;    ┆          │
│            ┆            ┆             ┆                   ┆   ┆          ┆             ┆ Mobile…          ┆          │
│ 25%        ┆ null       ┆ 2.4906e12   ┆ null              ┆ … ┆ 0.75     ┆ null        ┆ null             ┆ null     │
│ 50%        ┆ null       ┆ 5.0171e12   ┆ null              ┆ … ┆ 1.49     ┆ null        ┆ null             ┆ null     │
│ 75%        ┆ null       ┆ 7.5266e12   ┆ null              ┆ … ┆ 2.25     ┆ null        ┆ null             ┆ null     │
│ max        ┆ 2023-10-05 ┆ 1.0000e13   ┆ young.org         ┆ … ┆ 3.0      ┆ HTTPS       ┆ Opera/9.99.(X11; ┆ iOS      │
│            ┆ 23:58:52   ┆             ┆                   ┆   ┆          ┆             ┆ Linux x86_64; w… ┆          │
└────────────┴────────────┴─────────────┴───────────────────┴───┴──────────┴─────────────┴──────────────────┴──────────┘

## Custom Data Schema

In [19]:
custom_schema = {
    'date_time': pl.Utf8,
    'userid': pl.Utf8,
    'domain': pl.Utf8,
    'dlbytes': pl.Int64,
    'ulbytes': pl.Int64,
    'clientip': pl.Utf8,
    'serverip': pl.Utf8,
    'country': pl.Utf8,
    'txn_time': pl.Float64,
    'http_method': pl.Utf8,
    'user_agrent': pl.Utf8,
    'platform': pl.Utf8
}

In [22]:
df = pl.read_csv('course_file.csv', has_header=True, dtypes=custom_schema)

In [24]:
df.head(2)

shape: (2, 12)
┌────────────┬───────────────┬──────────────────┬─────────┬───┬──────────┬─────────────┬──────────────┬──────────┐
│ date_time  ┆ userid        ┆ domain           ┆ dlbytes ┆ … ┆ txn_time ┆ http_method ┆ user_agrent  ┆ platform │
│ ---        ┆ ---           ┆ ---              ┆ ---     ┆   ┆ ---      ┆ ---         ┆ ---          ┆ ---      │
│ str        ┆ str           ┆ str              ┆ i64     ┆   ┆ f64      ┆ str         ┆ str          ┆ str      │
╞════════════╪═══════════════╪══════════════════╪═════════╪═══╪══════════╪═════════════╪══════════════╪══════════╡
│ 2023-10-04 ┆ 7773153683656 ┆ ryan-wells.co.uk ┆ 872807  ┆ … ┆ 2.33     ┆ HTTPS       ┆ Mozilla/5.0  ┆ Android  │
│ 11:37:11   ┆               ┆                  ┆         ┆   ┆          ┆             ┆ (Windows; U; ┆          │
│            ┆               ┆                  ┆         ┆   ┆          ┆             ┆ Windows…     ┆          │
│ 2023-10-04 ┆ 1886351675683 ┆ hopkins.org      ┆ 50898   ┆ … ┆ 1.2      ┆ HTTP        ┆ Mozilla/5.0  ┆ Android  │
│ 12:17:07   ┆               ┆                  ┆         ┆   ┆          ┆             ┆ (Windows; U; ┆          │
│            ┆               ┆                  ┆         ┆   ┆          ┆             ┆ Windows…     ┆          │
└────────────┴───────────────┴──────────────────┴─────────┴───┴──────────┴─────────────┴──────────────┴──────────┘